repos:
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
      args: ['--line-length', '120']
      language_version: python3.11
-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.0
    hooks:
    - id: flake8
      args: ['--max-line-length', '120']